version: '3'

services:
  nginx:
    build:
      context: './bin/nginx'
      dockerfile: Dockerfile
    container_name: '${PROJECT_NAME}-nginx-server'
    restart: 'always'
    ports:
      - '${NGINX_HTTP_PORT}:80'
      - '${NGINX_HTTPS_PORT}:443'
    volumes:
      - ./app:/var/www/html
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php
  php:
    build:
      context: './bin/php'
      dockerfile: Dockerfile
    container_name: '${PROJECT_NAME}-php-fpm'
    restart: 'always'
    volumes:
      - ./app:/var/www/html
  database:
    image: mariadb/mariadb:${MARIADB_VERSION}
    container_name: '${PROJECT_NAME}-database'
    restart: 'always'
    ports:
      - '${MYSQL_HOST_PORT}:3306'
    volumes:
      - ${MYSQL_DATA_DIR-./data/mariadb}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mariadb}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PMA_VERSION}
    container_name: '${COMPOSE_PROJECT_NAME}-phpmyadmin'
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${PMA_HOST_PORT}:80'
    volumes:
      - /sessions
      - ${PHP_INI}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
